task: 'VAE-latentdim_128-sigma_0.8-bg_1.0-clip-bn_F'

seed: 42

log_dir: 'logs'
ckpt_dir: 'checkpoints'

data_path: 'data/single_cell_data_with_mask'
only_1st: False
mean: [6071.00008939, 1333.11164146, 5088.6889315, 5019.25101443]
std: [5493.51552474, 1109.11673063, 660.90377311, 704.11820438]
image_size: 32
split_ratio: 0.8

batch_size: 256
shuffle: True
num_workers: 4

model: 'VAE'
in_channels: 4
latent_dim: 128
use_bn: False
dropout: 0.0
layer_list: [2, 2, 2, 2]

lr_scheduler: 'StepLR'
lr: 0.03
step_size: 25
lr_decay: 0.8

loss:
  sigma: 0.8
  bg_var: 1.0

epochs: 500
save_interval: 10
