task: 'VAE-latentdim_128-sigma_0.8-bg_1.0-1st_chan'

seed: 42

log_dir: 'logs'
ckpt_dir: 'checkpoints'

data_path: 'data/single_cell_data_with_mask'
only_1st: True
mean: [6071.00008939, 6071.00008939, 6071.00008939, 6071.00008939]
std: [5493.51552474, 5493.51552474,  5493.51552474,  5493.51552474]
image_size: 32
split_ratio: 0.8

batch_size: 128
shuffle: True
num_workers: 4

model: 'VAE'
in_channels: 4
latent_dim: 128
use_bn: True
dropout: 0.0
layer_list: [2, 2, 2, 2]

lr_scheduler: 'StepLR'
lr: 0.03
step_size: 25
lr_decay: 0.8

loss:
  sigma: 0.8
  bg_var: 1.0

epochs: 500
save_interval: 10
